### ISSUE TITLE
How to center a div

### ISSUE THREAD

**Issue by devfemibadmus** [kshitijayamgar/webDevlopment#1]
I see you having issue centering your div after reviewing your codes, i have made some modification here they are below

```CSS
.container {
    /* if the container width is 100px how will its child makes 350px?
	width: 100px;
    */
    width: 100%; /* add width 100% to take full of device since this is the main container */
	height: 100vh;
	font-family: sans-serif;
	background: rgb(187, 187, 245);
	color: #0a0a0a; 
	align-items: center;
	align-content: center;
    /* I see you trying to center your container but its bad this way
	margin-top: 50px;
	margin-left: 30%;
	margin-right: 30%;
    */
    display: flex; /* Use flexbox to center the card */
    justify-content: center; /* Center the content horizontally */
}
```

you can replace this with ur `.container` all modify part are comment so you can understand. Below is my other suggestions

```CSS
/* Color Alternatives to White:
   - Off-White or Ivory: #F8F8F8 or #FFFFF0
   - Light Gray: #F0F0F0 or #EDEDED
   - Beige: #F5F5DC or #FFE4C4
   - Light Blue: #E6F7FF or #B3E0FF
   - Light Yellow: #FFFFE0 or #FFFACD
   - Light Green: #E6FFCC or #D0F0C0
   - Light Pink: #FFEBEB or #FFD9D9
   - Lavender: #E6E6FA or #CCCCFF
   - Peach: #FFDAB9 or #FFC0CB
   - Light Coral: #F08080 or #FF6F61
*/
```

Below are screenshot of before and after using the code i modify

Before
![_C__Users_devfe_Desktop_webDevlopment_index html(iPhone SE) (1)](https://github.com/kshitijayamgar/webDevlopment/assets/84607331/e9324a42-6575-4447-95c7-6466fc68fbb2)

After
![_C__Users_devfe_Desktop_webDevlopment_index html(iPhone SE)](https://github.com/kshitijayamgar/webDevlopment/assets/84607331/66da88f5-5c94-4759-992e-d8f3649ca70d)
